package fr.lbroquet.adventofcode2025.day7;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class TachyonManifoldTest {
    @Test
    void should_count_splits() {
        String input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """;
        char[][] map = input.lines().map(String::toCharArray).toArray(char[][]::new);
        TachyonManifold manifold = new TachyonManifold(map);
        assertThat(manifold.countSplits()).isEqualTo(21);
    }

    @Test
    void should_count_timelines() {
        String input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """;
        char[][] map = input.lines().map(String::toCharArray).toArray(char[][]::new);
        TachyonManifold manifold = new TachyonManifold(map);
        assertThat(manifold.countTimelines()).isEqualTo(40);
    }

    @Test
    void should_count_timelines_small() {
        String input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^2.....
                ...............
                ....1^.^3......
                ...............
                .....4^0 ......
                ...............
                """;
        char[][] map = input.lines().map(String::toCharArray).toArray(char[][]::new);
        TachyonManifold manifold = new TachyonManifold(map);
        assertThat(manifold.countTimelines()).isEqualTo(10);
    }
}